# Generated by Django 5.1.7 on 2025-03-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('clinic', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('profile_url', models.URLField()),
                ('phone', models.CharField(max_length=15, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('vcard_url', models.URLField()),
                ('cv_url', models.URLField(null=True)),
                ('photo_url', models.URLField()),
                ('languages', models.JSONField(blank=True, null=True)),
                ('hospitals', models.JSONField(blank=True, null=True)),
                ('specialisations', models.JSONField(blank=True, null=True)),
                ('educations', models.JSONField(blank=True, null=True)),
                ('work_experience', models.JSONField(blank=True, null=True)),
                ('apprenticeships', models.JSONField(blank=True, null=True)),
                ('publications', models.JSONField(blank=True, null=True)),
                ('researches', models.JSONField(blank=True, null=True)),
                ('awards', models.JSONField(blank=True, null=True)),
                ('competences', models.JSONField(blank=True, null=True)),
                ('memberships', models.JSONField(blank=True, null=True)),
                ('site_url', models.CharField(max_length=255, null=True)),
                ('media_urls', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
