# Generated by Django 5.1.7 on 2025-03-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apprenticeship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('year', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('year', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('year', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='apprenticeships',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='competences',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='educations',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='hospitals',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='memberships',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='publications',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='researches',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialisations',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='doctor',
            name='apprenticeships',
            field=models.ManyToManyField(blank=True, to='parser_app.apprenticeship'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='awards',
            field=models.ManyToManyField(blank=True, to='parser_app.award'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='competences',
            field=models.ManyToManyField(blank=True, to='parser_app.competence'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='educations',
            field=models.ManyToManyField(blank=True, to='parser_app.education'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospitals',
            field=models.ManyToManyField(blank=True, to='parser_app.hospital'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='languages',
            field=models.ManyToManyField(blank=True, to='parser_app.language'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='memberships',
            field=models.ManyToManyField(blank=True, to='parser_app.membership'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='publications',
            field=models.ManyToManyField(blank=True, to='parser_app.publication'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='researches',
            field=models.ManyToManyField(blank=True, to='parser_app.research'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialisations',
            field=models.ManyToManyField(blank=True, to='parser_app.specialisation'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='work_experience',
            field=models.ManyToManyField(blank=True, to='parser_app.workexperience'),
        ),
    ]
