# Generated by Django 5.1.7 on 2025-03-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_apprenticeship_award_competence_education_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
