# Generated by Django 5.1.7 on 2025-03-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_alter_doctor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprenticeship',
            name='year',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='year',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='year',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='year',
            field=models.CharField(null=True),
        ),
    ]
