# Generated by Django 5.1.7 on 2025-03-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0004_alter_apprenticeship_year_alter_award_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
