# Generated by Django 5.1.7 on 2025-03-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0005_alter_competence_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='specialisation',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
