# Generated by Django 5.1.7 on 2025-03-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0006_alter_award_name_alter_hospital_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='facebook',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='fax',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='instagram',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='linkedin',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='twitter',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='youtube',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
