# Generated by Django 5.1.7 on 2025-03-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0007_doctor_address_doctor_facebook_doctor_fax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='clinic',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='vcard_url',
            field=models.URLField(null=True),
        ),
    ]
