# Generated by Django 5.1.7 on 2025-03-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0008_alter_doctor_clinic_alter_doctor_photo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='clinic',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='facebook',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='fax',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='instagram',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='linkedin',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='site_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='twitter',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='youtube',
            field=models.TextField(null=True),
        ),
    ]
