# Generated by Django 5.1.6 on 2025-03-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0011_doctor_city_doctor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='info',
            field=models.TextField(null=True),
        ),
    ]
