# Generated by Django 5.1.6 on 2025-04-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0013_clinic_remove_doctor_clinic_doctor_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='source',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='apprenticeship',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apprenticeship',
            name='year',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='year',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='competence',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='cv_url',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='facebook',
            field=models.URLField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='fax',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='instagram',
            field=models.URLField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='linkedin',
            field=models.URLField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo_url',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='site_url',
            field=models.URLField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='twitter',
            field=models.URLField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='vcard_url',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='youtube',
            field=models.URLField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='year',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialisation',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='year',
            field=models.CharField(blank=True, null=True),
        ),
    ]
