# Generated by Django 5.1.6 on 2025-04-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0014_doctor_source_alter_apprenticeship_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='postcode',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
