# Generated by Django 5.1.6 on 2025-04-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0015_doctor_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialisation',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
