# Generated by Django 5.1.6 on 2025-04-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0016_specialisation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialisation',
            name='slug',
            field=models.SlugField(blank=True, max_length=10000, null=True, unique=True),
        ),
    ]
