# Generated by Django 5.1.6 on 2025-04-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0017_alter_specialisation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialisation',
            name='name',
            field=models.TextField(blank=True, default=None, unique=True),
            preserve_default=False,
        ),
    ]
