# Generated by Django 5.1.6 on 2025-04-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0018_alter_specialisation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialisation',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='specialisation',
            name='slug',
            field=models.SlugField(blank=True, max_length=10000, null=True),
        ),
    ]
