# Generated by Django 5.1.6 on 2025-04-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0019_alter_specialisation_name_alter_specialisation_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='source',
        ),
    ]
