# Generated by Django 5.1.6 on 2025-04-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0020_remove_doctor_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='source',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
